---
- name: Install Terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.11.14/terraform_0.11.14_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes  
    state: present

    